server:
  port: 8080
  # tomcat设置
  tomcat:
    # 开启日志访问
    max-threads: 1000
    min-spare-threads: 500
    uri-encoding: UTF-8
    basedir: ./
    accesslog:
      enabled: true
      pattern: "%h %I %{YYYY-MM-dd HH:mm:ss.SSS}t [%m %H %U] %s %b %Dms [%{req_param_data}r] [%{AppClientInfo}r] [%{zp-user-id}i] [%{User-Agent}i]"
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      force: true
      charset: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 200 #连接池的最大连接数
      minimum-idle: 50 #最小空闲连接数
management:
  endpoints:
    web:
      exposure: ## 暴露健康检测接口
        include: "health,info,dubbo-thread-pool"