spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/geek?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always