server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    password: 123456
    jedis:
      pool:
        max-active: 16
        min-idle: 8
        max-idle: 16
        max-wait: 6000